# Generated by Django 4.1 on 2024-04-04 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0003_alter_module_module_content'),
        ('accounts', '0002_otpverification'),
        ('courses', '0036_alter_course_date_generated'),
        ('sections', '0002_section_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pass', 'pass'), ('fail', 'fail')], max_length=4)),
                ('for_date', models.DateField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('on_time', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_test_results', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_test_results', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleVideos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module_video', models.URLField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_modules_course', to='courses.course')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_module_records', to='modules.module')),
            ],
        ),
        migrations.CreateModel(
            name='DeadlineGiven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField()),
                ('date_started', models.DateField(auto_now_add=True)),
                ('deadline_finished', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_deadlines', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_deadlines', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='TestFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_feedbacks', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_students', to='accounts.student')),
                ('testname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_feedback', to='progress.testresults')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='RevisionSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_revision_sections', to='courses.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_sections', to='sections.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_revision_sections', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'section')},
            },
        ),
        migrations.CreateModel(
            name='CourseCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_students', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_completed_course', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
