# Generated by Django 4.1 on 2024-04-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_alter_course_date_generated'),
        ('accounts', '0002_otpverification'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecompleted',
            name='completed_date',
            field=models.DateField(auto_now_add=True, default='2024-04-04'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='deadlinegiven',
            unique_together={('student', 'course', 'deadline')},
        ),
    ]
