# Generated by Django 4.1 on 2024-04-04 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification'),
        ('courses', '0038_alter_course_date_generated'),
        ('progress', '0002_coursecompleted_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deadlinegiven',
            unique_together={('student', 'course')},
        ),
    ]
