# Generated by Django 4.1 on 2024-04-07 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_module_module_content'),
        ('accounts', '0002_otpverification'),
        ('progress', '0003_alter_deadlinegiven_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedModules',
            fields=[
                ('date_completed', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('complete_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed', to='modules.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_models', to='accounts.student')),
            ],
        ),
    ]
