# Generated by Django 4.1 on 2024-04-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_completedmodules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedmodules',
            name='date_completed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
