# Generated by Django 4.1 on 2024-04-08 00:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_alter_course_date_generated'),
        ('progress', '0005_alter_completedmodules_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedmodules',
            name='course_belonged',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_modules_completed', to='courses.course'),
            preserve_default=False,
        ),
    ]
