# Generated by Django 4.1 on 2024-04-08 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_alter_course_date_generated'),
        ('progress', '0007_remove_completedmodules_course_belonged'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedmodules',
            name='course_belonged',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='course_modules_completed', to='courses.course'),
            preserve_default=False,
        ),
    ]
