# Generated by Django 4.1 on 2024-04-08 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0008_completedmodules_course_belonged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedmodules',
            name='course_belonged',
        ),
    ]
