# Generated by Django 4.1 on 2024-04-08 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_alter_course_date_generated'),
        ('progress', '0009_remove_completedmodules_course_belonged'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedmodules',
            name='course_belongs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules_completed', to='courses.course'),
            preserve_default=False,
        ),
    ]
