# Generated by Django 4.1 on 2024-04-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_section_completed_course'),
        ('progress', '0010_completedmodules_course_belongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedmodules',
            name='in_section',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='modules_completed', to='sections.section'),
            preserve_default=False,
        ),
    ]
