# Generated by Django 4.1 on 2024-04-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0011_completedmodules_in_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='total_marks',
            field=models.IntegerField(default=20),
        ),
    ]
