# Generated by Django 4.1 on 2024-05-17 15:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0069_alter_course_date_generated'),
        ('progress', '0012_testresults_total_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinCoursePassword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_for_course', to='courses.course')),
            ],
        ),
    ]
