# Generated by Django 4.1 on 2024-01-18 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0022_alter_course_date_generated'),
        ('accounts', '0002_otpverification'),
        ('sections', '0002_section_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precourse_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Test_space',
            fields=[
                ('question', models.CharField(max_length=250)),
                ('options_a', models.CharField(max_length=250)),
                ('options_b', models.CharField(max_length=250)),
                ('options_c', models.CharField(max_length=250)),
                ('options_d', models.CharField(max_length=250)),
                ('answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D'), ('N', 'None')], default='N', max_length=200)),
                ('level', models.CharField(choices=[('easy', 'easy'), ('meduim', 'medium'), ('hard', 'hard'), ('expert', 'expert')], default='easy', max_length=15)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Startcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_given', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_pretest', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Pretest_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('Correct', 'C'), ('Wrong', 'W')], max_length=14)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='coursetests.precourse_test')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.AddField(
            model_name='precourse_test',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precourse_questions', to='coursetests.test_space'),
        ),
        migrations.AddField(
            model_name='precourse_test',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
