# Generated by Django 4.1 on 2024-05-19 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursetests', '0002_alter_pretest_result_question'),
        ('courses', '0070_alter_course_date_generated'),
        ('accounts', '0002_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicTests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodic_test_number', models.IntegerField(default=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('given', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_tests', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_tests', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyCalculatedDailyModulesCompleted',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('total_avg_modules_pd', models.IntegerField(default=0)),
                ('average_modules_pd', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avg_daily_modules', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avg_daily_modules', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PeriodicTestQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_tests_questions', to='courses.course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_course_question', to='coursetests.test_space')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_tests_questions', to='accounts.student')),
                ('test_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='schedulerapp.periodictests')),
            ],
            options={
                'unique_together': {('student', 'course', 'question', 'test_no')},
            },
        ),
        migrations.CreateModel(
            name='DeadlineCalculated',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_generated', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='DailyModulesCompleted',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('daily_modules_completed', models.IntegerField(default=0)),
                ('total_modules_completed_till_yesterday', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_modules', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_modules', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'date')},
            },
        ),
    ]
