# Generated by Django 4.1 on 2024-05-26 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymodulescompleted',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
