# Generated by Django 4.1 on 2024-05-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerapp', '0002_alter_dailymodulescompleted_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='periodictests',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='periodictests',
            name='course',
        ),
        migrations.RemoveField(
            model_name='periodictests',
            name='student',
        ),
        migrations.DeleteModel(
            name='PeriodicTestQuestions',
        ),
        migrations.DeleteModel(
            name='PeriodicTests',
        ),
    ]
