# Generated by Django 4.1 on 2024-04-14 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0063_alter_course_date_generated'),
        ('sections', '0003_section_completed_course'),
        ('coursetests', '0002_alter_pretest_result_question'),
        ('accounts', '0002_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResultsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testtype', models.CharField(default='levelup', max_length=100)),
                ('testname', models.CharField(max_length=100)),
                ('answer', models.CharField(choices=[('r', 'r'), ('w', 'w'), ('na', 'na')], max_length=2)),
                ('date_given', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_test_result', to='courses.course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_test_results', to='coursetests.test_space')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_test_results', to='sections.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_data', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'testname')},
            },
        ),
        migrations.CreateModel(
            name='LevelsAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Expert', 'Expert')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels_allowed', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels_available', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'level')},
            },
        ),
        migrations.CreateModel(
            name='AttemptedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=100)),
                ('date_attempted', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempted_tests', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempted_tests', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'testname')},
            },
        ),
    ]
