# Generated by Django 4.1 on 2024-04-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification'),
        ('courses', '0065_alter_course_date_generated'),
        ('alltests', '0002_attemptedtest_testtype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attemptedtest',
            unique_together={('student', 'course', 'testname', 'date_attempted')},
        ),
    ]
