# Generated by Django 4.1 on 2024-04-15 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification'),
        ('courses', '0066_alter_course_date_generated'),
        ('alltests', '0003_alter_attemptedtest_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testresultsdetail',
            unique_together={('student', 'course', 'testname', 'date_given')},
        ),
    ]
