# Generated by Django 4.1 on 2024-04-15 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursetests', '0002_alter_pretest_result_question'),
        ('accounts', '0002_otpverification'),
        ('courses', '0067_alter_course_date_generated'),
        ('alltests', '0004_alter_testresultsdetail_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testresultsdetail',
            unique_together={('student', 'course', 'testname', 'date_given', 'question')},
        ),
    ]
