# Generated by Django 4.1 on 2024-05-29 17:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification'),
        ('courses', '0083_alter_course_date_generated'),
        ('alltests', '0005_alter_testresultsdetail_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicTestActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=100, unique=True)),
                ('timegenerated', models.DateField(default=datetime.date.today)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_tests_available', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_tests_available', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'testname')},
            },
        ),
        migrations.CreateModel(
            name='MissedPeriodicTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=100, unique=True)),
                ('timemissed', models.DateField(default=datetime.date.today)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_tests_missed', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_tests_missed', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'testname')},
            },
        ),
    ]
