# Generated by Django 4.1 on 2024-06-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alltests', '0006_periodictestactive_missedperiodictests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missedperiodictests',
            name='testname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='periodictestactive',
            name='testname',
            field=models.CharField(max_length=100),
        ),
    ]
