# Generated by Django 4.1 on 2024-01-18 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 18, 11, 53, 960143, tzinfo=datetime.timezone.utc)),
        ),
    ]
