# Generated by Django 4.1 on 2024-01-23 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 14, 21, 17, 80465, tzinfo=datetime.timezone.utc)),
        ),
    ]
