# Generated by Django 4.1 on 2024-02-03 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 12, 40, 5, 67386, tzinfo=datetime.timezone.utc)),
        ),
    ]
