# Generated by Django 4.1 on 2024-02-04 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 20, 30, 13, 596599, tzinfo=datetime.timezone.utc)),
        ),
    ]
