# Generated by Django 4.1 on 2024-02-17 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 0, 52, 41, 309009, tzinfo=datetime.timezone.utc)),
        ),
    ]
