# Generated by Django 4.1 on 2024-04-04 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 4, 6, 8, 20, 2736, tzinfo=datetime.timezone.utc)),
        ),
    ]
