# Generated by Django 4.1 on 2024-04-07 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 8, 1, 46, 36, 692141, tzinfo=datetime.timezone.utc)),
        ),
    ]
