# Generated by Django 4.1 on 2024-04-08 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 8, 5, 51, 36, 436110, tzinfo=datetime.timezone.utc)),
        ),
    ]
