# Generated by Django 4.1 on 2024-04-08 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 8, 6, 1, 38, 286861, tzinfo=datetime.timezone.utc)),
        ),
    ]
