# Generated by Django 4.1 on 2024-04-12 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0060_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 22, 5, 11, 242680, tzinfo=datetime.timezone.utc)),
        ),
    ]
