# Generated by Django 4.1 on 2024-04-14 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0063_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 0, 19, 53, 447006, tzinfo=datetime.timezone.utc)),
        ),
    ]
