# Generated by Django 4.1 on 2024-04-15 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0065_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 6, 43, 39, 306824, tzinfo=datetime.timezone.utc)),
        ),
    ]
