# Generated by Django 4.1 on 2024-04-16 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0067_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 1, 26, 51, 909048, tzinfo=datetime.timezone.utc)),
        ),
    ]
