# Generated by Django 4.1 on 2024-05-19 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0069_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 1, 3, 25, 603062, tzinfo=datetime.timezone.utc)),
        ),
    ]
