# Generated by Django 4.1 on 2024-05-25 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0078_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 25, 8, 22, 16, 112457, tzinfo=datetime.timezone.utc)),
        ),
    ]
