# Generated by Django 4.1 on 2024-05-29 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0082_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 23, 6, 43, 467702, tzinfo=datetime.timezone.utc)),
        ),
    ]
