# Generated by Django 4.1 on 2024-05-29 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0083_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 0, 22, 16, 484774, tzinfo=datetime.timezone.utc)),
        ),
    ]
