# Generated by Django 4.1 on 2024-06-01 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0084_alter_course_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_generated',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 13, 22, 7, 206679, tzinfo=datetime.timezone.utc)),
        ),
    ]
