# Generated by Django 4.1 on 2024-04-12 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_alter_course_date_generated'),
        ('sections', '0002_section_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_completed',
            name='course',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='completed_sections', to='courses.course'),
            preserve_default=False,
        ),
    ]
